---

- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/usecase1.yml

  tasks:
    - name: Provision virtual machine
      vmware_guest:
        hostname: '{{ vmware_hostname }}'
        username: '{{ vmware_username }}'
        password: '{{ vmware_password }}'
        validate_certs: no
        datacenter: '{{ vmware_datacenter }}'
        cluster: '{{ vmware_cluster }}'
        name: '{{ vm_name | default("webapp") }}'
        template: '{{ vmware_webapp_template }}'
      register: webapp_vm_provision

    - name: Add host to inventory
      add_host:
        name: web
        hostname: '{{ webapp_vm_provision.instance.ipv4 }}'

- hosts: web
  become: yes

  vars_files:
    - vars/usecase1.yml

  tasks:
    - name: Create user accounts
      user:
        name: '{{ item.name }}'
        password: '{{ item.password | hash("sha1") }}'
        state: present
      with_items:
        - '{{ system_users }}'
        - '{{ web_users }}'
        - '{{ dba_users }}'

    - name: Open firewall ports
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: '{{ item }}'
        cstate: NEW,ESTABLISHED
        jump: ACCEPT
        state: present
      with_items: '{{ open_ports }}'

    - name: Install Apache
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - httpd
        - mod_ssl

    - name: Install PHP modules
      pear:
        name: '{{ item }}'
        state: present
      with_items:
        - Archive_Tar
        - XML_RPC

    - name: Install MySQL repo
      yum:
        name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
        state: present

    - name: Install MySQL
      yum:
        name: mysql-community-server
        state: present
